### ISSUE TITLE
version 0.8.16b mirror incoming calls no longer works on non android stock phones

### ISSUE THREAD

**Issue by grenryd** [elbowz/xbmc.service.pushbullet#20]
Hello again

Thank for the fix on galaxy nexus (or all stock android).
I have been testing it now and it works great with the latest version. 0.8.16b

But I have one new problem with this version:
On my phone "Samsung Note 3" it no longer displays incoming call at all. Everything else seams to work fine but not incoming calls. I have tried it on 3 different computers. It's not really a problem because I can use version 0.8.12b for my phone and version 0.8.16b for my girlfriends phone. But I can't do any updates if you add any new cool stuff.

Here is my log with enabled debug: http://xbmclogs.com/show.php?id=350658
pastebin if xbmclogs.com is not working: http://pastebin.com/ua6TA4yp

**Comment by ruuk** [comment]
@elbowz - I recommend using message.get('title','') instead for items that might not be there, like in my fix eee437abbc1b145169dc1b121e2617d67a1031ce. There may be other places where we might want to do this because a lot of push fields are optional.

**Comment by elbowz** [comment]
Fixed here e7981bc77c6c105b61659c957599b08085af5d6f (I hope)

@grenryd - Again wait next 0.8.18b...and sorry again for the regression bug

@ruuk - You have right, I didn't know the `dict.get()` method with fallback default value. I did not done check (in the previous release) because I thought that was impossible there was a android notification without a **title**... I have mistake, Samsung have done one of it ;)

Take a look if now is it good? ...and always feel free to fix or correct my code. I like to learn as I said you :)

edit: if you want postpone 0.8.18b release for me it's ok...I think we do too many releases with few changes, and this is not a major bug...how do you prefer

**Comment by ruuk** [comment]
I think I will put it on my repository, as it was a user reported bug.

Also, I'm probably going to create another repository. I want to use it for pre-release/alpha/testing versions. It's useful for me because it makes it easier to get things I'm testing onto all my other devices, plus we can link to the zips there if we need a user to test something, but we would otherwise use it internally. I'll be adding it for use with my other addons in any case.

Also, I was wondering if you think we should drop the b and do more normal versions.

Example:
- 0.10.0a2 <- Private version (on my alpha repo)
- 0.10.0a4 <- Private versions (on my alpha repo)
- At this point we decide we wan't to stop adding things and prepare for release
- 0.10.0b2 <- On my current repo (beta)
- 0.10.0b4 <- On my current repo (beta)
- 0.10.0 <- Release to offical repository
- A significant bug is found
- 0.10.2b2 <- On my current repo (beta)
- Bug fix is fine
- 0.10.2 <- Release to offical repository

Or something like that?

**Comment by grenryd** [comment]
Hi 

I have been testing the latest code and all bugs are gone. Everything work as normal now. Great work guys. Big thanks !

PS it still shows version 0.8.16b in addon.xml

**Comment by ruuk** [comment]
> PS it still shows version 0.8.16b in addon.xml

Actually I just changed it about 5 minutes ago :)

Also, thanks for taking the time to test it directly from GitHub.

**Comment by elbowz** [comment]
@grenryd - say hello to your girlfriend ;)

@ruuk - I see that you have preserve the even number :)
I like your solution, and I don't have nothing to do in this revolution...

At the end for me is ok!

A (unrelated) question: How to develop? I mean the working directory...

Before work in a team, I had a symlink in _.xbmc/addons_ that point on my real project working directory (with .git folder and others stuff of my ide).

But now, If you release a new version and I start Kodi, all my project is overwritten and I lose .git (etc..)
